apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  KEYCLOAK_CLIENT_ID: flask-app
  KEYCLOAK_REALM: MyRealm
  KEYCLOAK_PUBLIC_URL: http://localhost:8080
  KEYCLOAK_INTERNAL_URL: http://auth:8080
  MQTT_BROKER_URL: broker.hivemq.com
  MQTT_BROKER_PORT: "1883"
  KC_HOSTNAME: localhost

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  KC_HOSTNAME: localhost

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  FLASK_SECRET: c3VwZXItc2VjcmV0LWtleQ==
  KEYCLOAK_CLIENT_SECRET: R2ZhaFNMZGlPYXBwSWFGRzlBSXAzVXVOOFVtMzZGU24=
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=
  KC_BOOTSTRAP_ADMIN_PASSWORD: YWRtaW4=
